# Stage 1: Build the Angular app
FROM node:18 as build-stage
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build --prod

# Stage 2: Serve the app with NGINX
FROM nginx:alpine
COPY --from=build-stage /app/dist/task-manager-app /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]